# Generated by Django 2.2.7 on 2019-11-11 20:42

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('codigo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha_subida', models.DateTimeField(default=datetime.datetime.now)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(upload_to='documentos/')),
            ],
        ),
    ]
