# Generated by Django 2.2.7 on 2019-11-14 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta',
            name='fecha_publicacion',
        ),
        migrations.AlterField(
            model_name='acta',
            name='fecha_subida',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
