# Generated by Django 2.2.7 on 2019-11-18 03:16

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('actas', '0002_auto_20191114_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
