# Generated by Django 2.2.7 on 2019-11-19 01:57

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0003_auto_20191118_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='acta',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Separar tags con comas', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
