# Generated by Django 2.2.7 on 2019-11-20 20:50

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0004_auto_20191118_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='archivo',
            field=models.FileField(storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='dialogosfaif'), upload_to=''),
        ),
    ]
