# Generated by Django 2.2.7 on 2019-11-21 19:55

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0005_auto_20191120_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='acta',
            name='archivo',
            field=models.FileField(blank=True, help_text='Máximo 5MB', null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='dialogosfaif'), upload_to=''),
        ),
    ]
