# Generated by Django 2.2.7 on 2019-11-22 02:46

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0006_auto_20191121_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='dialogosfaif'), upload_to='')),
                ('descripcion', models.TextField(help_text='Descripción de los que está ocurriendo en la imagen. Necesario para ser inclusivo con los estudiantes con visión limitada')),
            ],
        ),
    ]
