# Generated by Django 2.2.7 on 2019-12-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0010_auto_20191122_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='archivo',
            field=models.FileField(blank=True, help_text='Máximo 5MB', null=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='archivo',
            field=models.ImageField(upload_to='documentos/'),
        ),
    ]
